# Site settings
title: "Hello,World!"
description: "So I was feeling nostalgic."
baseurl: ""
url: "http://just-some-tests.github.io/"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "about"
    url: /about
  - title: "github"
    url: http://github.com/just-some-tests
  - title: "rss"
    url: /feed.xml
